[package]
name = "longtaco"
edition = "2024"

[dependencies]
actix-files = "0.6.6"
actix-multipart = "0.7.2"
actix-web = "4.11.0"
futures-util = "0.3.31"
rand = "0.9.2"
serde_json = "1.0.143"
tokio = { version = "1.47.1", features = ["fs"] }
zip = "4.5.0"
